import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import liff from '@line/liff';
import { useState } from "react";
import { useRouter } from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const router = useRouter();
  const [userInfo, setUserInfo] = useState({
    version: '',
    isInClient: false,
    isLoggedIn: false,
    os: '',
    lineVersion: '',
  });

  const handleCloseButton = () => {
    if (!liff.isInClient()) {
      window.alert(
        "This button is unavailable as LIFF is currently being opened in an external browser."
      );
    } else {
      liff.closeWindow();
    }
  }

  const handleGetInfo = () => {
    setUserInfo({
      version: liff.getVersion(),
      isInClient: liff.isInClient(),
      isLoggedIn: liff.isLoggedIn(),
      os: liff.getOS() || '',
      lineVersion: liff.getLineVersion() || '',
    });
  }

  const handleOpenExternalButton = () => {
    liff
    .sendMessages([
      {
        type: "text",
        text: "Hello, World!",
      },
    ])
    .then(() => {
      console.log("message sent");
    })
    .catch((err) => {
      console.log("error", err);
    });

    handleCloseButton();
  }

  const handleTransitionURL = () => {
    liff.openWindow({
      url: "https://team-lab.com",
      external: true,
    });
  }

  const handleTransitionEvent = () => {
    router.push('/event');
  }

  const handleTransitionMap = () => {
    router.push('/map');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div>LIFF APP</div>
          <div className={styles.ctas}>
            <button className={styles.primary} onClick={handleCloseButton}>Close Window</button>
            <button className={styles.secondary} onClick={handleGetInfo}>情報取得</button>
            <button className={styles.secondary} onClick={handleOpenExternalButton}>テキスト送信</button>
            <button className={styles.secondary} onClick={handleTransitionURL}>別サイト表示</button>
            <button className={styles.secondary} onClick={handleTransitionEvent}>イベント画面へ遷移</button>
            <button className={styles.secondary} onClick={handleTransitionMap}>マップ画面へ遷移</button>
          </div>
          <div>
            <pre>{JSON.stringify(userInfo, null, 2)}</pre>
          </div>
        </main>
      </div>
    </>
  );
}
